import { checkGrounding, visibleText, type GeneratedQuestion } from "@quizforge/core";
import type { JudgeResult } from "./judge.js";
import { quizMetrics } from "./lint.js";
import { cosine, maxPairwise, tfidfEmbedder } from "./similarity.js";
import { splitSections } from "./source.js";

/**
 * THE quality method. Every quiz generated in production and every quiz generated by the evals is scored by this one
 * function, so the numbers in Langfuse (names below), in Postgres and in CloudWatch mean the same thing everywhere.
 * Bump QUALITY_VERSION when anything here changes: scores are only comparable within one version.
 *
 * What differs between environments is only the INPUT, and it is recorded: the judge model and the number of judge
 * samples (the production worker is configured with the same judge as the CI evaluation).
 */
export const QUALITY_VERSION = "2026-10-08.1";

export type Lang = "pt" | "en" | "unknown";

const STOP: Record<"pt" | "en", Set<string>> = {
  pt: new Set(["que", "de", "para", "com", "uma", "um", "os", "as", "não", "do", "da", "em", "por", "se", "qual", "quais", "é", "são", "ao", "dos", "das", "pelo", "pela", "como"]),
  en: new Set(["the", "of", "and", "is", "to", "in", "which", "what", "that", "for", "are", "does", "with", "by", "it", "an", "be", "when", "how"]),
};

/** Cheap, deterministic language guess by stop-word share. Good enough to tell Portuguese from English. */
export function detectLanguage(text: string): Lang {
  const words = text.toLowerCase().normalize("NFC").split(/[^\p{L}]+/u).filter(Boolean);
  if (words.length < 8) return "unknown";
  const score = (l: "pt" | "en") => words.filter((w) => STOP[l].has(w)).length / words.length;
  const [pt, en] = [score("pt"), score("en")];
  if (Math.max(pt, en) < 0.05) return "unknown";
  return pt > en ? "pt" : "en";
}

export const quizText = (qs: GeneratedQuestion[]): string => qs.flatMap((q) => [q.prompt, ...q.options, q.explanation]).join("\n");

/** TF-IDF similarity metrics (free and deterministic, so they can run on every production quiz). */
export async function similarityScores(questions: GeneratedQuestion[], sourceText: string): Promise<Record<string, number>> {
  const sections = splitSections(sourceText).filter((s) => s.tokens >= 40);
  const chunks = (sections.length ? sections.map((s) => s.text) : [sourceText]).flatMap((t) => t.split(/\n\s*\n/)).filter((c) => c.trim().length > 30);
  const emb = tfidfEmbedder(chunks);
  const qText = (q: GeneratedQuestion) => `${q.prompt} ${q.options[q.correct[0]!]}`;
  const vecs = await emb.embed([...questions.map(qText), ...chunks]);
  const qv = vecs.slice(0, questions.length);
  const cv = vecs.slice(questions.length);
  const scores: Record<string, number> = {};
  scores.question_diversity = 1 - maxPairwise(qv);
  scores.relevance = qv.length ? qv.reduce((acc, v) => acc + Math.max(0, ...cv.map((c) => cosine(v, c))), 0) / qv.length : 0;
  // coverage: distinct sections hit by the quotes, relative to the best possible (needs a document with real structure)
  if (sections.length >= 3) {
    const hit = new Set<number>();
    for (const q of questions) {
      const quote = visibleText(q.sourceQuote);
      sections.forEach((s, i) => visibleText(s.text).includes(quote) && hit.add(i));
    }
    scores.coverage = Math.min(1, hit.size / Math.min(questions.length, sections.length));
  }
  return scores;
}

/** Weights of `quality_overall` (they sum to 1; a metric that does not apply, such as coverage on a flat document, is left out and the rest renormalised). */
export const QUALITY_WEIGHTS = { judge_overall: 0.45, lint_pass: 0.15, relevance: 0.15, question_diversity: 0.15, coverage: 0.1 } as const;
/** Hard requirements: a quiz that fails one is unusable, so `quality_overall` is 0 whatever the other metrics say. */
export const QUALITY_GATES = ["grounded", "language_match"] as const;

export interface QuizQuality {
  /** every metric is 0..1, higher is better; names are the Langfuse score names */
  scores: Record<string, number>;
  /** weighted average; undefined when the judge did not run, so two formulas are never mixed under one name */
  quality: number | undefined;
  gated: boolean;
}

export async function scoreQuiz(p: {
  questions: GeneratedQuestion[];
  sourceText: string;
  judge?: JudgeResult | undefined;
  /** Defaults to the language detected in the source document. */
  expectedLanguage?: Lang | undefined;
}): Promise<QuizQuality> {
  const m = quizMetrics(p.questions);
  const scores: Record<string, number> = {
    grounded: checkGrounding({ questions: p.questions }, p.sourceText).ok ? 1 : 0,
    lint_pass: m.lintPass,
    difficulty_spread: m.difficultySpread,
    ...(await similarityScores(p.questions, p.sourceText)),
  };
  const expected = p.expectedLanguage ?? detectLanguage(p.sourceText);
  if (expected !== "unknown") {
    const got = detectLanguage(quizText(p.questions));
    if (got !== "unknown") scores.language_match = got === expected ? 1 : 0;
  }
  if (p.judge) {
    scores.judge_overall = p.judge.overall;
    for (const k of ["faithfulness", "clarity", "distractors", "coverage", "difficulty_mix"] as const) scores[`judge_${k}`] = (p.judge.scores[k] - 1) / 4;
  }

  const gated = QUALITY_GATES.some((g) => scores[g] !== undefined && scores[g]! < 1);
  if (!p.judge) return { scores, quality: undefined, gated };
  const used = (Object.keys(QUALITY_WEIGHTS) as (keyof typeof QUALITY_WEIGHTS)[]).filter((k) => scores[k] !== undefined);
  const total = used.reduce((a, k) => a + QUALITY_WEIGHTS[k], 0);
  const quality = gated ? 0 : used.reduce((a, k) => a + QUALITY_WEIGHTS[k] * Math.min(1, Math.max(0, scores[k]!)), 0) / total;
  return { scores, quality, gated };
}
